apiVersion: v1
kind: Service
metadata:
  name: fast-api-python-service
spec:
  selector:
    app: fast-api-python
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-python
spec:
  selector:
    matchLabels:
      app: fast-api-python
  replicas: 2
  template:
    metadata:
      labels:
        app: fast-api-python
    spec:
      containers:
      - name: fast-api-python
        image: fast-api-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000