apiVersion: v1
kind: Service
metadata:
  name: fast-api-python-service
spec:
  selector:
    app: fast-api-python
  ports:
  - protocol: "TCP"
    targetPort: 8000
    port: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-python
spec:
  selector:
    matchLabels:
      app: fast-api-python
  replicas: 2
  template:
    metadata:
      labels:
        app: fast-api-python
    spec:
      containers:
      - name: fast-api-python
        image: docker.io/library/fast-api-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_CONN
          value: "mysql+pymysql://root:password@mycluster:3306/records_db"